name: test-and-publish
on:
  push:
    branches:
      - "*"
jobs:
  test-and-publish:
    name: Test and publish
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    concurrency:
      group: test-and-publish
      cancel-in-progress: true
    permissions:
      # for git fetch
      contents: read
      # for npm publish provenance
      id-token: write
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: 1.0.18
      - run: bun install
      - run: bun run types
      - run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npm publish --access public --provenance || true
        if: github.ref == 'refs/heads/main'
